notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: 3xScF4vMLNUV2NHPKmcSY2fwj+oUKJsdcVh8xrIo2XElvkq8r6aP6IkAg3cVwRztfSnHt6sL9paLC2rLwC70chMHhSPI36wpMbRndhy1GBMFaVqlOjsLVVCd7YpNr0T59h4PmdjeZYxwtTn5VMZIxEZ0AhNkQ1Ja8E27BFkGroLwjN0rtj4liK6rUNcb1mN7k5e2Sh7lvAy3F1ckxlB7imgT3Ar/DMoYjCSbDZbhXiSHjo2CHy9EkwTP8EnDGxDBdfNwzOtTqNDNzkX34p63pevwt6f+6eHFOPw5VhWZ3PlJiBeX7dINBnSytvUPwPPGtxj5N6wASsCEvx5fHPcqlJKPzX7FuaCdx6/PpIH/lKVL/57S0qi2ZRDGM7o7C3nnc588mU8cuTPsVAlERDSWfow7pU3u/AFg2eTfiGuol175Tx7k1xs/P0gxCzIjqxCxSAdNqOVZ7+AAYdQjS94mSwzg1MEnBz7QyTTYHAXhHkqv5n6nb7c1EoKkFACoofOCwd1SoGoA9EDmBpXN45BKbm3I8BNmquA6noUAPZT9vsAXFXpIXbnpWUJ4ctlF54wofQFK4B6qJpH4yB7JerZyHS+7x3ahfkoQDtR5FBfKx0ONhLEqnxq0YBijjE8mJBNLR+kc70riwMlSTIIqACRdL9I4LMvdreyTykmWYLvos1o=
  api_key:
    secure: sOx44qlNLgECg6WylNfi+aSEPca0DVpi0dSgdyEpU1T7RbrUYevOueSzWzefEiyWuqwbx9enFXzrZPSKll/QsdKvCk7wduerhQ8IeFExqpI9JY2vI3zz66git4EmElnyTKLrjZZveTAVTM7rFHhDki6HHWeBQBI8R7tXTH/aA//5fLh/wTWW6QsFQeljJkCZdJbu3Ec/OgerpFtLINlBcXtg5ekrEohKBaXVgrWq7eEbXTT34Es97fH9v+D1b6icm/8svCKm2CSouhhQ/avAflcIRkV2dIxRLa3YamBmqmT8Md+//efvzqfLTyfbVutOq6pbK6+OUNfsAAUO+m91iQsMKpfl5WP1EWOsqVh/0IcJXOV70pVApjO3oDttY/sLdGK9C0AqPoIUhzxbebcf/h6PrF3wMlFsSpSPLarTiNKlyzOGhrmpIE20VYSbCl4t7SHjdahnEraZcw4zTBrrTURZ6JznjoUyjlBPVpIFswuw6K4lXp94cz0uZd/t05zDNoVU6UVi1RkJkO9sc7tsjhkxRUcdxh/C4DydJeFoSwK2ebyLJGYtXMX1FXP0j97Lkyg7grYwn9uOsAkd7Dr7n0GbSaBaHkzKGv0mQdIbnXMK7ZnxuR9vXX9Y9ybB6XhRUaGhwre6rPb06WTfEDipGJC7oJnMNca2oIUZCu5zD2o=
  on:
    tags: true
